"""create logs and threat_alerts tables

Revision ID: dc51ef6bbb8a
Revises: 
Create Date: 2026-08-24 13:54:29.527406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc51ef6bbb8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_event_type'), 'logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_logs_source_ip'), 'logs', ['source_ip'], unique=False)
    op.create_table('threat_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.String(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_alerts_threat_type'), 'threat_alerts', ['threat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_alerts_threat_type'), table_name='threat_alerts')
    op.drop_table('threat_alerts')
    op.drop_index(op.f('ix_logs_source_ip'), table_name='logs')
    op.drop_index(op.f('ix_logs_event_type'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
